artifact_location: /Users/daniel/Documents/GitHub/projects/enterprise-rag/mlflow_data/528960460468396225
creation_time: 1777611042720
experiment_id: '528960460468396225'
last_update_time: 1777611042720
lifecycle_stage: active
name: Livingstone_RAG_System
trace_location: null
workspace: default
